### ISSUE TITLE
npm run build: eleventy: command not found

### ISSUE THREAD

**Issue by pascalandy** [gregwolanski/eleventy-tailwindcss-alpinejs-starter#6]
## log

```
➜  my-website-name git:(master) npm run build

> @ build /Volumes/960G/_pascalandy/11_FirePress/Github/random-stuff/gregwolanski:eleventy-tailwindcss-alpinejs-starter/my-website-name
> ELEVENTY_PRODUCTION=true eleventy && NODE_ENV=production postcss styles/tailwind.css --o _site/style.css && cleancss _site/style.css -o _site/style.css

sh: eleventy: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ build: `ELEVENTY_PRODUCTION=true eleventy && NODE_ENV=production postcss styles/tailwind.css --o _site/style.css && cleancss _site/style.css -o _site/style.css`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p_andy/.npm/_logs/2021-01-03T21_06_14_594Z-debug.log
➜  my-website-name git:(master) npm run start

> @ start /Volumes/960G/_pascalandy/11_FirePress/Github/random-stuff/gregwolanski:eleventy-tailwindcss-alpinejs-starter/my-website-name
> eleventy --serve & postcss styles/tailwind.css --o _tmp/style.css --watch

sh: eleventy: command not found
TypeError: Invalid PostCSS Plugin found at: plugins[1]

(@/Volumes/960G/_pascalandy/11_FirePress/Github/random-stuff/gregwolanski:eleventy-tailwindcss-alpinejs-starter/my-website-name/postcss.config.js)
    at /usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/plugins.js:72:15
    at Array.forEach (<anonymous>)
    at plugins (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/plugins.js:58:13)
    at processResult (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/index.js:33:14)
    at /usr/local/lib/node_modules/postcss-cli/node_modules/postcss-load-config/src/index.js:94:14
    at async Promise.all (index 0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `eleventy --serve & postcss styles/tailwind.css --o _tmp/style.css --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p_andy/.npm/_logs/2021-01-03T21_06_28_673Z-debug.log
```

**Comment by pascalandy** [comment]
## videocast

https://user-images.githubusercontent.com/6694151/103488829-01033d00-4dde-11eb-8393-d31d89cb4808.mp4

**Comment by pascalandy** [comment]
Sorry, I suck lol. I cannot use `:` (gregwolanski:eleventy-tailwindcss-alpinejs-starter)
I used `_` (gregwolanski_eleventy-tailwindcss-alpinejs-starter)
